nowijnah/ajouproject

- public/index.html
- src/App.js
- src/components/comments/Comment.js
- src/components/comments/CommentInput.js
- src/components/comments/CommentList.js
- src/components/comments/Comments.js
- src/hooks/commentsHook.js
> [#1] 댓글+답글 컴포넌트

- src/components/Footer.js
> [#7] refactoring footer component 

- src/components/posts/UploadPost.js
- src/components/posts/ViewPost.js
> [#10] ViewPost 페이지 변경

- package.json
- src/App.js
- src/components/Navbar.js
- src/pages/Home.js
- src/pages/MyPage.js
페이지 라우팅 구현 및 UI 컴포넌트 개선
1. 페이지 라우팅 구현
- MyPage → UploadPost → ViewPost 페이지 전환
- useNavigate 훅을 활용한 Upload 버튼 기능 개선
2. MyPage 컴포넌트 개선
- 상단: 흰색 배경, 이름/소속 중앙 정렬
- 하단: 아주대학교 블루(rgb(0, 51, 161)) 배경
- 포트폴리오 카드 그리드 레이아웃
- 포트폴리오 섹션 아이콘 우측 정렬
- 포트폴리오 제목 강조
3. Home 페이지 개선
- Material-UI 컴포넌트 적용
- 반응형 디자인 적용
> feat: Implement page routing and enhance UI components

- src/components/Navbar.js
- src/components/auth/AuthContext.js
- src/components/common/ContentList.js
- src/pages/Home.js
- src/pages/MyPage.js
- src/pages/companies/CompanyCard.js
- src/pages/companies/CompanyPage.js
- src/pages/portfolios/PortfolioCard.js
- src/pages/portfolios/PortfolioPage.js
1. 사용자 역할별 게시물 필터링
- 학생: portfolios 컬렉션
- 기업: companies 컬렉션
- 교수: labs 컬렉션
2. 게시물 정렬 기능 추가
- 최신순: createdAt 기준 내림차순 정렬
- 인기순: likeCount 기준 내림차순 정렬
- 댓글순: commentCount 기준 내림차순 정렬
3. Firebase Firestore 복합 인덱스 구현
- portfolios 컬렉션: authorId(ASC) + createdAt(DESC)
- companies 컬렉션: authorId(ASC) + createdAt(DESC)
- 사용자 역할별 적절한 카드 컴포넌트 렌더링
- 복합 인덱스를 사용
- MyPage.js
- AuthContext.js
- ContentList.js
> 마이페이지에서 사용자별 게시물 필터링, 정렬 기능 구현했습니다.

- src/components/posts/BasePostUpload.js
- src/components/posts/BasePostView.js
> feat : added keywords section

- src/App.js
- src/components/auth/AuthContext.js
- src/components/posts/BasePostUpload.js
- src/components/posts/BasePostView.js
- src/pages/ProfilePage.js
개선 사항
- 게시글 작성자만 수정
- 게시글 작성자 프로필 열람
- 게시글 링크 처리
> [#27] fixed codes

- src/components/common/ContentList.js
- src/pages/MyPage.js
- src/pages/labs/LabCard.js
- src/pages/labs/LabPage.js
- 연구실 정보를 표시하는 LabCard 컴포넌트 구현
- ContentList에 연구실 카드 타입 추가 및 연동
- MyPage에서 교수 역할일 때 연구실 카드 표시 기능 추가
- 마이페이지에서 역할별 소속 정보 표시 로직 개선
1. LabCard 컴포넌트:
- 연구실 정보 표시를 위한 카드 컴포넌트 구현
- 기존 카드 컴포넌트들과 동일한 스타일 및 기능 제공
2. ContentList 수정:
- 'lab' 타입 추가 및 LabCard 렌더링 로직 구현
- 연구실 데이터 처리 로직 개선
3. MyPage 개선:
- 교수 역할일 때 LabCard 사용하도록 수정
- 역할별 소속 정보 표시 조건 추가 (학생만 '아주대학교' 표시)
- Closes #<issue-number>
> feat: 연구실 정보 페이지 구현 및 마이페이지 UI 개선

- src/components/posts/BasePostUpload.js
> [#34] edit button fixed

- src/components/common/ContentCard.js
- src/components/posts/BasePostView.js
- src/hooks/useLike.js
- src/pages/companies/CompanyCard.js
- src/pages/labs/LabCard.js
- src/pages/portfolios/PortfolioCard.js
- useLike 훅을 사용한 좋아요 카운팅 기능 구현
- 미리보기 모드에서 좋아요 버튼 및 댓글 섹션 숨김 처리
> feat: 좋아요 카운팅 기능 및 미리보기 모드 개선

- src/components/Navbar.js
- src/components/common/ContentCard.js
- src/components/common/ContentList.js
- src/components/common/styles.js
- src/components/portfolio/FilterSection.js
- src/components/posts/BasePostView.js
- src/pages/companies/CompanyPage.js
- src/pages/labs/LabPage.js
- src/pages/portfolios/PortfolioPage.js
기업 페이지에서 일부 오류가 있지만.. 해결하겟습니다..
> 필터 박스 삭제 및 카드리스트 대표 이미지 확대

- src/components/comments/CommentInput.js
- src/components/comments/Comments.js
구현한 기능
- 댓글 입력 칸 프로필 가져오기
- 승인된 회사만 댓글 작성
> [#43] 댓글 - 사용자 식별

- package.json
- src/components/common/ContentList.js
- src/components/search/SearchComponent.js
- src/pages/companies/CompanyPage.js
- src/pages/labs/LabPage.js
- src/pages/portfolios/PortfolioPage.js
검색 기능 추가
- 제목, 부제목, 내용, 키워드 검색 가능
> [#45] 검색 기능 추가

- .gitignore
- package.json
- src/components/Navbar.js
- src/components/common/styles.js
- src/components/posts/BasePostUpload.js
> feat: navbar 개선 및 markdown toolbar 추가

- src/components/posts/BasePostView.js
- 게시글 삭제 기능 구현
- 댓글, 좋아요, 파일 등 연관 데이터 일괄 삭제 처리
- 삭제 확인 다이얼로그 추가
- 작성자만 삭제 가능하도록 권한 처리
- 삭제 버튼 UI/UX 개선
> feat: 게시글 삭제 기능 추가

- src/components/Navbar.js
> [#59] feat : edit navbar

- src/components/auth/AuthContext.js
- src/components/auth/ProtectedRoute.js
- src/components/common/AnimatedLoading.js
- src/components/common/LoadingSpinner.js
- src/components/common/PageLoading.js
- src/pages/companies/CompanyPage.js
- src/pages/labs/LabPage.js
- src/pages/portfolios/PortfolioPage.js
- components/common 폴더에 LoadingSpinner, AnimatedLoading, PageLoading 컴포넌트 추가
- ProtectedRoute에 로딩 상태 표시 기능 개선
- PortfolioPage, LabPage, CompanyPage에 애니메이션 로딩 화면 적용
> feat: 로딩 화면 개선 적용

- src/components/comments/Comment.js
- src/hooks/useReplies.js
Comment.js: 날짜 표시 형식 변경 및 답글 버튼 표시 로직 수정
useReplies.js: 날짜 변환 로직 개선 및 반환값 수정
> fix: 답글 UI 및 타임스탬프 표시 개선

- src/components/auth/AuthContext.js
- src/components/auth/SignIn.js
- src/components/auth/SignUp.js
- webpack.config.js
구글회원가입 & 로그인 로직 같음 -> 기업만 회원가입 가능하도록
jobDescription에 "교원"포함시 professor로
> [#73] 회원가입/로그인 수정

- src/App.js
- src/components/Navbar.js
- src/components/auth/AuthContext.js
- src/components/home/NoticeSection.js
- src/pages/Home.js
- src/pages/admin/AdminNotices.js
- src/pages/admin/AdminPage.js
- src/pages/admin/AdminSoftcon.js
- src/pages/admin/AdminUsers.js
- src/pages/notices/NoticeList.js
- src/pages/notices/NoticeView.js
- 관리자 대시보드 페이지 추가
- 공지사항 관리 기능 구현
- 사용자 관리 페이지 개발
- 소프트콘 프로젝트 관리 페이지 추가
- 관리자 권한 기반 페이지 접근 제어
- 공지사항 CRUD 기능
- 사용자 역할 및 계정 상태 관리
- 소프트콘 프로젝트 관리 페이지
- 공지사항 이미지/파일 업로드
- 이메일 발송 기능
- 사용자 제재 시스템
- 소프트콘 프로젝트 데이터 조회 및 사용자 매칭
> feat(admin): 관리자 대시보드 및 공지사항 관리 기능 구현
